version: '3'
services:
  db:
    build: ./db
    image: ealge-oj-db
    container_name: eagle-oj-db
    environment:
      MYSQL_ROOT_PASSWORD: eagle_oj
    restart: always
    volumes:
      - $PWD/data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
  judger:
    image: d87904488/eagle-oj-judger
    container_name: eagle-oj-judger
    restart: always
    ports:
      - "5000:5000"